### ISSUE TITLE
Changing the contrast in the 3D slicer for better visualization

### ISSUE THREAD

**Issue by bianchijonas1** [DCBIA-OrthoLab/SlicerCMF#12]
Hello. 
In the latest 3D slicer 4.11.0 (windows 2020-06-08) I cannot change the contrast of the volume for better visualization like I can do in slicer 4.10 (dragging the left button of the mouse in the sagittal/axial or coronal views to upwards/downwards/left and right).

This is not a CMF module problem, it is a Slicer version problem. Please if necessary move this issue.
Thank you

**Comment by pieper** [comment]
Hi - 

With recent versions, Slicer no longer puts you in window/level mode by default, so you need to click the middle icon in the toolbar here (or use the submenu to get some other useful modes).

https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#mouse-modes
