### ISSUE TITLE
MeshtoLabelMap

### ISSUE THREAD

**Issue by luciacev** [DCBIA-OrthoLab/SlicerCMF#20]
@bpaniagua @allemangD @jcf
[MeshtoLabel_Map_bug .docx](https://github.com/DCBIA-OrthoLab/SlicerCMF/files/5633213/MeshtoLabel_Map_bug.docx)

**Comment by bpaniagua** [comment]
From @luciacev 

When we load a CBCT scan and a VTK  model in Slicer 4.11 ( constructed in Slicer 4.11) , they seem oriented  correctly:\

![image](https://user-images.githubusercontent.com/2599368/101025985-55e43700-3544-11eb-901e-0c70ec85e0fd.png)


But when we run Mesh to Label Map if we use the  same CBCT as the reference image it    creates  an inverted segmentation ( It is flipped 180degrees and labels all the outside of the condyle).

![image](https://user-images.githubusercontent.com/2599368/101026017-5e3c7200-3544-11eb-9b2d-400aa025a27f.png)


 if we do not use the CBCT scan as the reference image and enter the image spacing (0.08, 0.08 .0.08), Mesh to Label Map runs and generates a condyle but is is flipped 180 degrees.

**Comment by pieper** [comment]
Almost certainly related to this change: https://discourse.slicer.org/t/model-files-are-now-saved-in-lps-coordinate-system/10446

**Comment by allemangD** [comment]
This should be resolved by https://github.com/NIRALUser/MeshToLabelMap/pull/10.
