### ISSUE TITLE
Extension "CMFreg" not displaying in the SlicerCMF Index

### ISSUE THREAD

**Issue by bianchijonas1** [DCBIA-OrthoLab/SlicerCMF#22]
The Extension " CMFreg" is not displaying among the others extensions when you click in the Slicer CMF icon. 

![image (1)](https://user-images.githubusercontent.com/47431886/107104431-7647a080-67d6-11eb-8749-f0c41cd92843.png)

However, you can find it if you go to the extension by yourself

![image](https://user-images.githubusercontent.com/47431886/107104449-865f8000-67d6-11eb-975b-228296f17261.png)

**Comment by allemangD** [comment]
The CMFreg extension introduces a few modules. In my PR I've added a link to the Surface Registration module.

Does this make sense? Should we link a different module, or perhaps link to multiple modules?

**Comment by luciacev** [comment]
@bpaniagua @allemangD @jcfr 
This issue was not solved. :-)
CMFreg extension modules should be listed in the SlicerCMF index, as it includes both Voxel registration and Surface Registration module, as well as other modules.
Please link the multiple modules.
Thanks.

**Comment by allemangD** [comment]
The new index now appears on stable 4.11.20210226.

![screenshot](https://user-images.githubusercontent.com/10702931/125298152-e44c4280-e2f5-11eb-8b12-6d925f02d492.png)
