### ISSUE TITLE
Fix build errors reported after building Slicer against VTK9

### ISSUE THREAD

**Issue by jcfr** [DCBIA-OrthoLab/SlicerCMF#24]
* [x] https://github.com/NIRALUser/ShapePopulationViewer/issues/55
* [x] https://github.com/NIRALUser/SPHARM-PDM/issues/61
* [x] https://github.com/DCBIA-OrthoLab/CMFreg/issues/34

**Comment by allemangD** [comment]
Closing since all issues are now resolved.
